# Generated by Django 4.2.18 on 2025-02-05 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0012_alter_slider_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 11, 5, 49, 955518, tzinfo=datetime.timezone.utc)),
        ),
    ]
