# Generated by Django 4.2.18 on 2025-02-06 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0013_alter_slider_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 9, 46, 26, 975357, tzinfo=datetime.timezone.utc)),
        ),
    ]
